export enum RoleEnum{
  CAN_CREATE = "CAN_CREATE",
  CAN_UPDATE = "CAN_UPDATE",
  CAN_READ = "CAN_READ",
  CAN_DELETE = "CAN_DELETE",
CAN_SEARCH_MACHINE = "CAN_SEARCH_MACHINE",
  CAN_START_MACHINE = "CAN_START_MACHINE",
  CAN_STOP_MACHINE = "CAN_STOP_MACHINE",
  CAN_RESTART_MACHINE = "CAN_RESTART_MACHINE",
  CAN_CREATE_MACHINE = "CAN_CREATE_MACHINE",
  CAN_DESTROY_MACHINE = "CAN_DESTROY_MACHINE"
}
